FROM tomcat:8.5-jre8

MAINTAINER Pauwel Demeyer <pdemeyer@gmail.com>

# Add my property file
# ADD servoy.properties $SERVOY_INSTALL_DIR/application_server/

# Define default command.
# CMD ["./servoy_docker.sh"]
